squashfs-tools/pseudo.c

Segfault happens when attempting to dump pseudo files in SQUASHFS_TRACE
mode after attempting to dereference NULL pseudo pointer.
Signed-off-by: Mohamad Ayyash mkayyash@google.com

mksquashfs: Fix segfault when SQUASHFS_TRACE is enabled and no -pf flag

---

squashfs-tools/unsquashfs.c

Fixes a bug in which security capabilities were not properly set on
written files.  chown(2) resets all capabilities so it should be run
before setting xattrs instead of afterwards.

unsquashfs: modify xattrs after other changes

---

squashfs-tools/unsquashfs.c

If character device files have extended attributes then
unsquashfs will incorrectly create them as block
device files. This patch checks if the file is character
device file in case it has extended attributes.

fix device type handling with extended attributes

---

squashfs-tools/mksquashfs.c

It is nice if the user interface of wrapper scripts can display a
progress bar to the user without having to display the detailed
information about the generated file. This can be achieved easily
by the new -quiet option. This is optionally already used by e.g.
https://github.com/vaeth/squashmount/

mksquashfs: enable -quiet option

---

squashfs-tools/unsquashfs.c

The option to display the superblock information currently give a
rounded value of the bytes used by the filesystem.
There are use cases in which knowing the exact value is very valuable.
This commit just adds this information.

unsquashfs: add code to dump the exact bytes used

---

squashfs-tools/mksquashfs.c
squashfs-tools/unsquashfs.c

This patch, when merged, adds an -offset option to skip n bytes which is very useful in situations where the squashfs image doesn't start at byte 0 of the file. This is quite common in the embedded space.
Patch for unsquashfs originally created by Yura Siamashka.
Patch for mksquashfs created by myself.

Add -offset option to skip n bytes

---

squashfs-tools/mksquashfs.c

For one of our projects ([1]), we need to distribute a rather large
rootfs containing cross-compile toolchains for every platform we
support. In general, we distribute this rootfs as a .tar.gz and
user usernamespaces on a user's machine to allow an unpriviledged
user to make use of this rootfs. We want to make use of the same
image on CI systems, however, the large uncompressed size of the
rootfs makes this impractical due to CI system disk space limitations
(on the other hand, we do tend to have sudo access on these systems,
since their abstrcation expose VMs with root access).
To work around this, we also distribute the rootfs as squashfs
image, thus alleviating the need to uncompress in image and allowing
the system to work in limited disk space sitatuions. This presents
another …

mkquashfs: Add `-noId` option to leave the uid/gid table uncompressed

---

squashfs-tools/mksquashfs.c
squashfs-tools/unsquashfs.c

From glibc 2.25 release notes:
https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html
"* The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.
This means that in a future release, the macros “major”, “minor”, and
“makedev” will only be available from <sys/sysmacros.h>."
See glibc bug https://sourceware.org/bugzilla/show_bug.cgi?id=19239 .

mksquashfs/unsquashfs: fix compilation with glibc 2.25+

---

squashfs-tools/xattr.h

In the non-XATTR_SUPPORT part the return type of write_xattr() does not match XATTR_SUPPORT, preventing compilation.

Fix return type of write_xattr

---

squashfs-tools/unsquashfs.c

Fix two deficiencies in unsquashfs: unix domain sockets were not created; and devnode major/minor numbers in the range 256-4095 were truncated to 8 bits.
Trivial test shell scripts attached (as .txt, because github).
I do not know best practices for portability in this repo; this code could certainly be wrapped in #ifdef linux is that is desirable.
[test-devnodes.sh.txt](https://github.com/plougher/squashfs-tools/files/3591619/test-devnodes.sh.txt)
[test-sockets.sh.txt](https://github.com/plougher/squashfs-tools/files/3591620/test-sockets.sh.txt)

Improve unsquashfs handling of special files

---

squashfs-tools/Makefile

This updates URLs for a few compression libraries, which have moved since the Makefile instructions were written.
Also, instructions now refer to the appropriate compressor arg, not always "the XZ_SUPPORT line below".

Fix typos, update URLs in squashfs-tools Makefile

---

squashfs-tools/mksquashfs.h

On gcc-10 (and gcc-9 -fno-common) build fails as:
```
cc ... -o mksquashfs
ld: read_fs.o:(.bss+0x0):
multiple definition of `fwriter_buffer'; mksquashfs.o:(.bss+0x400c90): first defined here
ld: read_fs.o:(.bss+0x8):
multiple definition of `bwriter_buffer'; mksquashfs.o:(.bss+0x400c98): first defined here
```
gcc-10 will change the default from -fcommon to fno-common:
https://gcc.gnu.org/PR85678.
The error also happens if CFLAGS=-fno-common passed explicitly.
Reported-by: Toralf Förster
Bug: https://bugs.gentoo.org/706456

squashfs-tools: fix build failure against gcc-10

---

squashfs-tools/squashfs_swap.h

Depending on the Linux distribution and compiler, the squashfs_swap.h file is included before endian.h, thus taking into consideration the code inside __BIG_ENDIAN `#if` even the system being little endian. A pratical reproduction of this problem is seen when compiling for Android. Including endian.h header ensures __BYTE_ORDER is defined before use and solves the issue.

Include endian.h before using __BYTE_ORDER  in squashfs_swap.h

---

squashfs-tools/xattr.h

`write_xattr` returns a boolean indicating success (TRUE/non-zero) or failure (FALSE/0).
The no-op implementation (`XATTR_SUPPORT=0`) always return 0 which is used as return value from `set_attributes` and treated as a failure in `writer` thread.
This patch just makes that "no-op `write_xattr`" is always successful.

Unsquashfs: fix always failing when build without xattr support

---

squashfs-tools/unsquashfs.c

With this patch unsquashfs displays progress whenever percentage changes.
Before the progress was very irregular (for example 0% - 54% - 100%) and indeterministic (those numbers were different between different runs with the same inputs).
The cause is that the `progress_bar` function updates progress only if `current` is a multiple of 100.  However `current` counts both filesystem objects (regular files, symlinks, etc) *and* data blocks. Therefore `current` becomes a multiple of 100 very rarely (if ever), hence the problem.
Closes: #113

unsquashfs: improved progress bar when stdout is not a terminal

---

squashfs-tools/Makefile

In case INSTALL_DIR is overridden with a staged install location, using
INSTALL_DIR for the symlink target path prefix will yield an incorrect location
for the final installation.
Because the symlink itself is already installed to INSTALL_DIR, simply removing
the INSTALL_DIR prefix suffices as a fix.
Note that using $DESTDIR/$INSTALL_DIR where appropriate can avoid this type of
issue, but that can be considered a future enhancement.

Avoid use of INSTALL_DIR for symlink targets

---

squashfs-tools/unsquash-4.c

If there are no fragments (as per the super block fragment count),
the fragment table is not accessed. In that case, it makes no sense
to check the fragment table location or assume anything about it.
It could reasonably be set to e.g. SQUASHFS_INVALID_BLK like the
other fields, which trips this check.
Furthermore, the kernel side implementation also does not perform
this check if the fragment count is zero. So with this check in
place, `unsquashfs` is no longer able to unpack images that the
kernel happily accepts as valid.

Don't sanity check fragment table location if there are no fragments

---

generate-manpages/install-manpages.sh

This helps binary reproducibility.
Signed-off-by: Alexander Kanavin <alex@linutronix.de>

install-manpages.sh: do not write original timestamps into .gz metadata

---

squashfs-tools/progressbar.c

Avoid progressbar counter overflow when there are large number of blocks (>2G with 32-bit integer) in a filesystem.

avoid progressbar counter overflow

---

squashfs-tools/unsquashfs.c

Removed redundant `else` statements from the read_super() function.

read_super() function cleanup

---

squashfs-tools/mksquashfs.c
squashfs-tools/unsquashfs.c

All compilers set `__linux__`, but `linux` may not be defined, and usage was mixed.  Use `__linux__` everywhere instead.

Move sysinfo.h into the linux-only section, should fix build on MacOS.

---

squashfs-tools/unsquashfs.c

Currently the include of sys/sysctl.h is guarded and done only for FreeBSD system. Remove this to fix compilation error on macos following the same pattern done in mksquashfs.c
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

Unsquashfs: fix compilation error for missing sysctl.h on macos

---

squashfs-tools/xattr.c

This restores the fix from c5db34e , which was somehow lost in 83b2f3a . `j` is not available after the loop is done, we need to use i. We use `i - 1` because, of course, list indexes start at 0.
Fixes https://github.com/plougher/squashfs-tools/issues/230

xattr: fix out of bounds access (again)

---

squashfs-tools/xz_wrapper.c

Add option to configure preset, lc, lp and pb lzma parameters. -Xpreset can be both a level or set to 'extreme' to use the lzma extreme compression options.
New option added:
-Xpreset
-Xlc
-Xlp
-Xpb
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>

xz_wrapper: support multiple lzma configuration options

---

ACTIONS-README
squashfs-tools/action.c

This request is revival of the closed "-half-fragments" command option.
https://github.com/plougher/squashfs-tools/pull/19
But implemented as a test action.
This is basically a copy-and-paste of the "filesize()" test action, except performing reminder calculation with block size.

add tailsize() to test actions.

---

ACTIONS-README

When I requested pulling tailsize(), I did copy-and-paste code of tailsize_range() with misunderstanding it were part of tailsize().
https://github.com/plougher/squashfs-tools/pull/266
But later, I noticed there is filesize_range() test action documented apart from filesize().
This pull request is to remove this inconsistency by adding tailsize_range() to document.
Sorry for previous half-baked one.

add tailsize_range(min,max) to doc.

---

squashfs-tools/xz_wrapper.c
squashfs-tools/xz_wrapper_extended.c

This sets LZMA2 options pb=2, lp=2, lc=2 as the default with the ARM64 filter as those are good for ARM64 code (all instructions are 4 bytes and 4-byte aligned). pb=2 is a default from the preset. lc=2 is needed because the sum lc+lp must not exceed 4 and the default is lc=3.
The ARM64 filter requires liblzma >= 5.4.0. It will build against older liblzma but then the filter won't be available. An alternative could have been to use
#ifndef LZMA_FILTER_ARM64
#define LZMA_FILTER_ARM64 LZMA_VLI_C(0x0A)
#endif
which would allow building against older liblzma and make the filter available once liblzma is upgraded, without requiring a recompilation of squashfs-tools.
The help text lists `arm64` even if built against pre-5.4.0.
Linux 6.7 will hopefully include the ARM64 filter. …

Add ARM64 filter support

---

squashfs-tools/mksquashfs.h
squashfs-tools/signals.h
squashfs-tools/unsquashfs.c

- it lacks sigtimedwait(2) and sigwaitinfo(2) just like Darwin
- there is no lutimes(2) but we can emulate it with utimensat(2)
- squashfs-tools/mksquashfs.h references pthread_mutex_t so include the header for it

Fix build on OpenBSD

---

squashfs-tools/memory_compat.h

I think it was left over after a509bba0c15b3bac4257eb42cf3ade518a6d5c77

mksquashfs: remove old reference to phys_mem

---

examples/pseudo-file.example

Addresses typos like `pseduo` to `pseudo`, `modifiy` to `modify`, `exmaple` to `example`.
Since squashfs-tools circa v4.5, it is possible for pseudo files to be created with custom timestamps. The same changes to pseudo-file.example now reflects those.
Reference:
* https://github.com/plougher/squashfs-tools/issues/98
* https://github.com/plougher/squashfs-tools/commit/aa5a6d76f587417f9434f57e03eb9544f1219f7f/squashfs-tools/pseudo.c

Typo fixes in pseudo-file.example and add custom timestamp option

---

ACKNOWLEDGEMENTS
squashfs-tools/Makefile
squashfs-tools/lzma_xz_wrapper.c
squashfs-tools/xz_wrapper.c
squashfs-tools/xz_wrapper_extended.c

Add support for ARM64 and RISC-V filters.
Optimize LZMA2 settings for existing filters. It's the last commit. I'm not sure if this change is acceptable as is.
Trivial whitespace fixes and HTTP to HTTPS URL changes are included too.
Feel free to pick the commits you like and tweak them too if you wish. Or, of course, I can edit based on feedback. :-)
@plougher: I sent you an email on 2024-07-31 and a reminder on 2024-08-22. I haven't gotten any replies, so I assume emails are getting lost somewhere. There is no rush as the kernel patches will only be in Linux 6.12 (apparently I have misunderstood something about merge window timing). So if you are busy, don't worry about the emails or this PR. Among a few other things, the first email included things that are related to this PR, so it …

XZ: Support ARM64 and RISC-V filters

---

squashfs-tools/pseudo.c

Resolve `l` type pseudo links before copying them in. 
Closes https://github.com/plougher/squashfs-tools/issues/289
```console
❯ take /tmp/mksquashfs-test
❯ echo hello > hello.txt
❯ ln -s hello.txt hello.link
❯ echo 'hello l hello.link' > pf.txt
❯ mkdir empty
❯ ll
total 12K
drwxrwxr-x 2 lalten lalten 4,0K Okt  9 21:55 empty
lrwxrwxrwx 1 lalten lalten    9 Okt  9 21:55 hello.link -> hello.txt
-rw-rw-r-- 1 lalten lalten    6 Okt  9 21:55 hello.txt
-rw-rw-r-- 1 lalten lalten   19 Okt  9 22:00 pf.txt
❯ ~/squashfs-tools/squashfs-tools/mksquashfs empty img.sqfs -pf pf.txt -exit-on-error -info -all-root -reproducible -mkfs-time 0 -root-time 0 -all-time 0
Parallel mksquashfs: Using 16 processors
Creating 4.0 filesystem on img.sqfs, block size 131072.
hello l 06002 0 36890207 0 1
file /hello, …
```

Resolve `l` type pseudo links

---

USAGE
manpages/mksquashfs.1
manpages/sqfstar.1
squashfs-tools/zstd_wrapper.c

These levels correspond to the --fast option of the zstd program,
and offers better compression speed for worse compression rate.
Closes #303

Support negative levels for zstd compression

---

squashfs-tools/error.h
squashfs-tools/mksquashfs.c
squashfs-tools/print_pager.h
squashfs-tools/unsquash-3.c
squashfs-tools/unsquash-4.c
squashfs-tools/unsquashfs.c

Some format specifiers did not match given arguments. I have added a compiler attribute to make these violations directly visible in the future.
The already existing violations are fixed with this pull request as well.

Fix format specifiers

---

squashfs-tools/mksquashfs.h

I got a compile error when trying to build squashfs-tools on macOS:
```
./mksquashfs.h:217:13: error: call to undeclared function 'pathconf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
217 |         path_max = pathconf(".", _PC_PATH_MAX);
|                    ^
./mksquashfs.h:217:27: error: use of undeclared identifier '_PC_PATH_MAX'
217 |         path_max = pathconf(".", _PC_PATH_MAX);
|                                  ^
```
I think clang might be a bit stricter than gcc, so it wanted an extra include.

Need to include unistd.h before using pathconf

---

squashfs-tools/tar.c

These commits fix different issues in sqfstar's tar parser and partially
depend on each other to mitigate the discussed issues fully:
1. Simple undefined C behaviour
Signed integer overflows are undefined behaviour and should be avoided.
From a C perspective, I do not care too much about them, but they can
lead to crashes later on in the code, e.g. because sqfstar does not
expect to encouter actually negative numbers for sizes later on.
Commits:
- sqfstar: prevent tarfile size overflows
- sqfstar: prevent st_rdev signed integer overflows
- sqfstar: terminate pax extended header string
Proof of Concepts:
This crashes sqfstar because of negative sizes:
```
cat > poc.tar.zst.b64 << EOF
KLUv/WQABe0BAPh1d3UAMDAwNjQ0IAAwgP/+MCAyMgAgMAB1c3RhcgAwCwCQ4H4AGsCGAL9BMgCX
JdW6AGKcxpUNoD09ASJ2tBTh
EOF …
```

sqfstar: improve tar parser stability

---

squashfs-tools/thread.h

Fix build error on macos:
```
In file included from mksquashfs_help.c:35:
./thread.h:46:39: error: unknown type name 'pthread_mutex_t'; did you mean 'pthread_attr_t'?
46 | extern void wait_thread_idle(int tid, pthread_mutex_t *mutex);
|                                       ^~~~~~~~~~~~~~~
|                                       pthread_attr_t
```
I noticed this issue when adding squashfs 4.7 to the OpenWrt. If you have a better fix, please ignore this PR. Ref: https://github.com/openwrt/openwrt/actions/runs/15440483743/job/43456872621

thread: add the missing pthread.h header

---

squashfs-tools/print_pager.h

When building with musl:
print_pager.h:33:25: error: unknown type name 'pid_t'
33 | extern void wait_to_die(pid_t process);
|                         ^~~~~
print_pager.h:34:25: error: unknown type name 'pid_t'
34 | extern FILE *exec_pager(pid_t *process);
|                         ^~~~~
print_pager.h uses pid_t and FILE, so add the required #includes to ensure that these are defined.

print_pager: add missing includes

---

squashfs-tools/sort.c

The error message for invalid priority values showed an incorrect range of -32767:32768, while the actual range check was for -32768:32767.

sort: Fix incorrect priority range in error message
